__title__ = 'mindsdb_native'
__package_name__ = 'mindsdb_native'
__version__ = '2.38.2'
__description__ = "MindsDB's goal is to make it very simple for developers to use the power of artificial neural networks in their projects."
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb_native'
__pypi__ = 'https://pypi.org/project/mindsdb'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2018- mindsdb'
